kind: pipeline
type: docker
name: ciem-front-end-deploy

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./.yarn-cache
        - ./node_modules

  - name: install
    image: node:alpine
    commands:
      - yarn config set cache-folder .yarn-cache
      - yarn install --pure-lockfile

  - name: package
    image: node:alpine
    commands:
      - yarn build

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./.yarn-cache
        - ./node_modules

  - name: deploy-test
    image: docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker build -t ciem_front_end_test:${DRONE_BUILD_NUMBER} .
      - docker stop ciem_front_end_test &> /dev/null || true
      - docker run --rm -p 8800:80 -d --name=ciem_front_end_test ciem_front_end_test:${DRONE_BUILD_NUMBER}
    when:
      ref:
        - refs/heads/release-*
      event:
        - push

trigger:
  ref:
    - refs/heads/release-*
  event:
    - push

volumes:
  - name: cache
    host:
      path: /tmp/drone/yarn-cache
  - name: docker
    host:
      path: /var/run/docker.sock